module.exports.HttpCode = Object.freeze({
    OK: 200,
    CREATED: 201,
    NO_CONTENT: 204,
    NOT_FOUND: 404,
    UNAUTHORIZED: 403,
    INTERNAL_SERVER_ERROR: 500,
    BAD_REQUEST: 400
})

module.exports.HttpText = Object.freeze({
    OK: "OK",
    CREATED: "CREATED",
    NO_CONTENT: "NO CONTENT",
    NOT_FOUND: "NOT FOUND",
    UNAUTHORIZED: "UNAUTHORIZED",
    INTERNAL_SERVER_ERROR: "INTERNAL SERVER ERROR",
    BAD_REQUEST: "BAD REQUEST"
})